### ISSUE TITLE
Charakternamen - Abstammung wird automatisch zurückgesetzt

### ISSUE THREAD

**Issue by skeshta** [Snizzle/german-name-generator#1]
Im Charakternamen-Generator wird die Abstammung automatisch zurückgesetzt, wenn man Folgendes tut:

(1) Über die Navigationsleiste  eine Abstammung für den Charakternamen-Generator auswählen.
(2) Rechts über das Menü eine andere Abstammung auswählen.
(3) Einen der neu generierten Namen anklicken. (Es öffnet sich der Charakterbogen.)
(4) Den Charakterbogen schließen.
(5) Jetzt ist die Abstammung wieder dieselbe, die in (1) ausgewählt wurde.

**Comment by skeshta** [comment]
Die Abstammung wird auch zurückgesetzt, wenn man in (2) ein anderes Geschlecht auswählt.

**Comment by Snizzle** [comment]
Das Problem trat tatsächlich auch für Orte auf und konnte jetzt behoben werden.
Danke für die Meldung!
