### ISSUE TITLE
Speichern vom Charakterbogen aus?

### ISSUE THREAD

**Issue by skeshta** [Snizzle/german-name-generator#2]
Ein Feature Request:

Momentan kann man Charaktere/Orte nur speichern, wenn man in der Namensliste auf ein kleines Icon ganz rechts klickt.

Wäre es möglich, dass man Charaktere auch direkt vom Charakterbogen aus speichern kann? (Und für Orte dann genauso.)

**Comment by Snizzle** [comment]
Klar wäre das möglich und ist sogar geplant!
Ich stelle mir ein ähnliches Icon im Titel der Seite vor (wo auch der Name des Characters / Ortes steht).

**Comment by Snizzle** [comment]
Ein entsprechender Button wird im nächsten Release zur Verfügung stehen.
